# Generated by Django 4.2.2 on 2023-06-17 22:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True, verbose_name='Nama Kategori')),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('no_whatsup', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('isi', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kontak',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('keterangan', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar/profil', verbose_name='Gambar (1920 x 1200 pixel)')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True, verbose_name='Judul')),
                ('gambar_slide', models.ImageField(null=True, upload_to='gambar/slide', verbose_name='Gambar (1920 x 880 pixel)')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Slide',
            },
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True, verbose_name='Nama')),
                ('pekerjaan', models.CharField(max_length=200, null=True, verbose_name='Pekerjaan')),
                ('gambar_testimoni', models.ImageField(null=True, upload_to='gambar/testimoni', verbose_name='Gambar (90 x 90 pixel)')),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Testimoni',
            },
        ),
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('wa', models.CharField(max_length=200, null=True, verbose_name='No Whatsapp')),
                ('alamat', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Custumer',
            },
        ),
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=200, null=True, unique=True)),
                ('gambar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/bahan', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_satu', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/bahan', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_dua', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/bahan', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_tiga', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/bahan', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_empat', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/bahan', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_lima', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/bahan', verbose_name='Gambar (600 x 600 pixel)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('keterangan', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('harga', models.PositiveIntegerField(null=True)),
                ('no_whatsup', models.PositiveBigIntegerField(null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('diskon', models.IntegerField(blank=True, default=0, null=True, verbose_name='Diskon (%)*)Kosongi')),
                ('dibeli', models.IntegerField(blank=True, default=0, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan', to='website.kategori')),
            ],
            options={
                'verbose_name_plural': 'Bahan Meubel',
            },
        ),
    ]
