# Generated by Django 4.2.2 on 2023-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan',
            name='keterangan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='keterangan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimoni',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
    ]
