# Generated by Django 4.2.2 on 2023-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_bahan_keterangan_alter_custumer_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahan',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
