# Generated by Django 5.0.1 on 2024-06-16 15:25

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_detailtransaksi_bahan'),
        ('website', '0003_bahan_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200, null=True, unique=True)),
                ('gambar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/produk', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_satu', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/produk', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_dua', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/produk', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_tiga', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/produk', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_empat', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/produk', verbose_name='Gambar (600 x 600 pixel)')),
                ('gambar_lima', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[600, 600], upload_to='gambar/produk', verbose_name='Gambar (600 x 600 pixel)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('keterangan', models.TextField(null=True)),
                ('harga', models.PositiveIntegerField(null=True)),
                ('no_whatsup', models.PositiveBigIntegerField(null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('diskon', models.IntegerField(blank=True, default=0, null=True, verbose_name='Diskon (%)*)Kosongi')),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('dibeli', models.IntegerField(blank=True, default=0, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='website.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.DeleteModel(
            name='Bahan',
        ),
    ]
