# Generated by Django 5.0.1 on 2024-06-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_chatid_statis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statis',
        ),
        migrations.AlterModelOptions(
            name='chatid',
            options={'verbose_name_plural': 'Chat ID'},
        ),
    ]
