# Generated by Django 5.0.1 on 2024-06-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_statis_alter_chatid_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimoni',
        ),
    ]
