# Generated by Django 4.2.2 on 2023-06-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=200, null=True)),
                ('tanggal_booking', models.DateField(blank=True, null=True)),
                ('jam_booking', models.CharField(blank=True, max_length=50, null=True)),
                ('wa_kirim', models.CharField(blank=True, max_length=200, null=True, verbose_name='No Whatsapp')),
                ('alamat_kirim', models.CharField(blank=True, max_length=300, null=True)),
                ('total_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('keterangan_pesanan', models.CharField(blank=True, choices=[('ditempat', 'ditempat'), ('dilokasi', 'dilokasi')], max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Order', 'Order'), ('Lunas', 'Lunas'), ('Pengiriman', 'Pengiriman'), ('Selesai', 'Selesai'), ('Gagal', 'Gagal')], default='Order', max_length=200, null=True)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='gambar/bukti')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('custumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='website.custumer')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=200, null=True)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('bahan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.bahan')),
            ],
            options={
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
