# Generated by Django 4.2.2 on 2023-06-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='jam_booking',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='tanggal_booking',
        ),
    ]
