# Generated by Django 4.2.2 on 2023-06-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bahan_stock'),
        ('cart', '0004_alter_transaksi_keterangan_pesanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='alamat_kirim',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='bukti_bayar',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='total_transaksi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='wa_kirim',
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custumer', to='website.custumer'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='keterangan_pesanan',
            field=models.CharField(blank=True, choices=[('Jemput', 'Jemput'), ('Antar', 'Antar')], max_length=200, null=True),
        ),
    ]
