# Generated by Django 4.2.2 on 2023-06-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bahan_stock'),
        ('cart', '0005_remove_transaksi_alamat_kirim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.custumer'),
        ),
    ]
