# Generated by Django 4.2.2 on 2023-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_transaksi_total_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(blank=True, choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas'), ('Pengiriman', 'Pengiriman'), ('Selesai', 'Selesai'), ('Gagal', 'Gagal')], default='Belum Lunas', max_length=200, null=True),
        ),
    ]
