# Generated by Django 4.2.2 on 2023-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_transaksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='token_payment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
