# Generated by Django 5.0.1 on 2024-06-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_detailtransaksi_bahan'),
        ('website', '0004_produk_delete_bahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtransaksi',
            name='produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.produk'),
        ),
    ]
