# Generated by Django 5.0.1 on 2024-06-18 13:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_detailtransaksi_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
                ('keterangan', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('setela_diskon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={'ordering': ('-no_transaksi',), 'verbose_name_plural': 'Detail Transaksi'},
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.produk'),
        ),
    ]
