# Generated by Django 5.0.1 on 2024-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_produk_alter_detailtransaksi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='setela_diskon',
        ),
        migrations.AddField(
            model_name='produk',
            name='setelah_diskon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
