# Generated by Django 5.0.1 on 2024-06-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_produk_setela_diskon_produk_setelah_diskon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='setelah_diskon',
            new_name='setela_diskon',
        ),
    ]
